typography_spectrum: 0.5907681554090232
color:
  brandColors:
    - '#f2d7a2'
    - '#d7bb89'
    - '#a9b2b6'
    - '#bb8c62'
    - '#6c684d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8404626669362187
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Mary Schultz
  email: marydschultz@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c5a35ba-bfba-454a-ab8f-d5c0bee8377e.jpg
name: marydschultz
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Private Journal
    id: 4072e79e-eea6-4bd5-ab9d-ecd789471b14
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b224ef5-e42f-47b4-bd75-69f9b39e5947.jpg
title: tastefulfool
description: ''
purpose: []
