layout_spectrum: 0.48942822334356606
typography_spectrum: 0.4382912728469819
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.2905617111828178
  lightness: 0.8788286251947284
  saturation: 0.10892844083718956
  rhythmicContrast: 0.019558773143216968
name: tastefulfool
favicon: null
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
