typography_spectrum: 0.4382912728469819
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.2905617111828178
  lightness: 0.8788286251947284
  saturation: 0.10892844083718956
  rhythmicContrast: 0.019558773143216968
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48942822334356606
analytics:
  google: null
  facebook: null
  twitter: null
name: shadow selves
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: on the road
    id: b80b9f6d-2384-4913-8262-40e2f5b0f920
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b224ef5-e42f-47b4-bd75-69f9b39e5947.jpg
title: null
purpose: []
