name: tastefulfool
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5413990046363324
title: tastefulfool
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9f4fe'
    - '#050a10'
    - '#4c5761'
    - '#bdb3a4'
    - '#921314'
  brandStrength: 0
  lightness: 0.6470204105135053
  saturation: 0.9151220978237689
  rhythmicContrast: 0.75
purpose: []
