name: marydschultz
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b224ef5-e42f-47b4-bd75-69f9b39e5947.jpg
layout_spectrum: 0.8404626669362187
typography_spectrum: 0.5907681554090232
author:
  name: Mary Schultz
  email: marydschultz@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c5a35ba-bfba-454a-ab8f-d5c0bee8377e.jpg
navigation:
  - name: Private Journal
    id: 4072e79e-eea6-4bd5-ab9d-ecd789471b14
    type: content
title: ''
description: selves
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f0f1ec'
    - '#3c3d42'
    - '#bfbab9'
    - '#7c7673'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 1
purpose: []
